// AUTO-GENERATED by scripts/compile-agents.ts — DO NOT EDIT
// Source: config/cognitive-types.yaml

export type CognitiveType = 'skill' | 'agent' | 'prompt';

export const COGNITIVE_SUBDIRS: Record<CognitiveType, string> = {
  skill: 'skills',
  agent: 'agents',
  prompt: 'prompts',
};

export const COGNITIVE_FILE_NAMES: Record<CognitiveType, string> = {
  skill: 'SKILL.md',
  agent: 'AGENT.md',
  prompt: 'PROMPT.md',
};

export const AGENTS_DIR = '.agents';
