// AUTO-GENERATED by scripts/compile-agents.ts — DO NOT EDIT
// Source: agents/*.yaml

import { homedir } from 'os';
import { join } from 'path';
import { existsSync } from 'fs';
import { xdgConfig } from 'xdg-basedir';
import type { AgentConfig, AgentType } from '../../../core/types.ts';

const home = homedir();
// Use xdg-basedir (not env-paths) to match OpenCode/Amp/Goose behavior on all platforms.
const configHome = xdgConfig ?? join(home, '.config');
const codexHome = process.env.CODEX_HOME?.trim() || join(home, '.codex');
const claudeHome = process.env.CLAUDE_CONFIG_DIR?.trim() || join(home, '.claude');

export const agents: Record<AgentType, AgentConfig> = {
  'adal': {
    name: 'adal',
    displayName: 'AdaL',
    dirs: {
      skill: { local: '.adal/skills', global: join(join(home, '.adal'), 'skills') },
      agent: { local: '.adal/agents', global: join(join(home, '.adal'), 'agents') },
      prompt: { local: '.adal/prompts', global: join(join(home, '.adal'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.adal'));
    },
  },
  'amp': {
    name: 'amp',
    displayName: 'Amp',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(configHome, 'agents'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(configHome, 'agents'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(configHome, 'agents'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(configHome, 'amp'));
    },
  },
  'antigravity': {
    name: 'antigravity',
    displayName: 'Antigravity',
    dirs: {
      skill: { local: '.agent/skills', global: join(join(home, '.gemini/antigravity'), 'skills') },
      agent: { local: '.agent/agents', global: join(join(home, '.gemini/antigravity'), 'agents') },
      prompt: { local: '.agent/prompts', global: join(join(home, '.gemini/antigravity'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.agent')) ||
        existsSync(join(home, '.gemini/antigravity'))
      );
    },
  },
  'augment': {
    name: 'augment',
    displayName: 'Augment',
    dirs: {
      skill: { local: '.augment/skills', global: join(join(home, '.augment'), 'skills') },
      agent: { local: '.augment/agents', global: join(join(home, '.augment'), 'agents') },
      prompt: { local: '.augment/prompts', global: join(join(home, '.augment'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.augment'));
    },
  },
  'claude-code': {
    name: 'claude-code',
    displayName: 'Claude Code',
    dirs: {
      skill: { local: '.claude/skills', global: join(claudeHome, 'skills') },
      agent: { local: '.claude/agents', global: join(claudeHome, 'agents') },
      prompt: { local: '.claude/prompts', global: join(claudeHome, 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(claudeHome);
    },
  },
  'cline': {
    name: 'cline',
    displayName: 'Cline',
    dirs: {
      skill: { local: '.cline/skills', global: join(join(home, '.cline'), 'skills') },
      agent: { local: '.cline/agents', global: join(join(home, '.cline'), 'agents') },
      prompt: { local: '.cline/prompts', global: join(join(home, '.cline'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.cline'));
    },
  },
  'codebuddy': {
    name: 'codebuddy',
    displayName: 'CodeBuddy',
    dirs: {
      skill: { local: '.codebuddy/skills', global: join(join(home, '.codebuddy'), 'skills') },
      agent: { local: '.codebuddy/agents', global: join(join(home, '.codebuddy'), 'agents') },
      prompt: { local: '.codebuddy/prompts', global: join(join(home, '.codebuddy'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.codebuddy')) ||
        existsSync(join(home, '.codebuddy'))
      );
    },
  },
  'codex': {
    name: 'codex',
    displayName: 'Codex',
    dirs: {
      skill: { local: '.agents/skills', global: join(codexHome, 'skills') },
      agent: { local: '.agents/agents', global: join(codexHome, 'agents') },
      prompt: { local: '.agents/prompts', global: join(codexHome, 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(codexHome) ||
        existsSync('/etc/codex')
      );
    },
  },
  'command-code': {
    name: 'command-code',
    displayName: 'Command Code',
    dirs: {
      skill: { local: '.commandcode/skills', global: join(join(home, '.commandcode'), 'skills') },
      agent: { local: '.commandcode/agents', global: join(join(home, '.commandcode'), 'agents') },
      prompt: { local: '.commandcode/prompts', global: join(join(home, '.commandcode'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.commandcode'));
    },
  },
  'continue': {
    name: 'continue',
    displayName: 'Continue',
    dirs: {
      skill: { local: '.continue/skills', global: join(join(home, '.continue'), 'skills') },
      agent: { local: '.continue/agents', global: join(join(home, '.continue'), 'agents') },
      prompt: { local: '.continue/prompts', global: join(join(home, '.continue'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.continue')) ||
        existsSync(join(home, '.continue'))
      );
    },
  },
  'crush': {
    name: 'crush',
    displayName: 'Crush',
    dirs: {
      skill: { local: '.crush/skills', global: join(join(home, '.config/crush'), 'skills') },
      agent: { local: '.crush/agents', global: join(join(home, '.config/crush'), 'agents') },
      prompt: { local: '.crush/prompts', global: join(join(home, '.config/crush'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.config/crush'));
    },
  },
  'cursor': {
    name: 'cursor',
    displayName: 'Cursor',
    dirs: {
      skill: { local: '.cursor/skills', global: join(join(home, '.cursor'), 'skills') },
      agent: { local: '.cursor/agents', global: join(join(home, '.cursor'), 'agents') },
      prompt: { local: '.cursor/prompts', global: join(join(home, '.cursor'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.cursor'));
    },
  },
  'droid': {
    name: 'droid',
    displayName: 'Droid',
    dirs: {
      skill: { local: '.factory/skills', global: join(join(home, '.factory'), 'skills') },
      agent: { local: '.factory/agents', global: join(join(home, '.factory'), 'agents') },
      prompt: { local: '.factory/prompts', global: join(join(home, '.factory'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.factory'));
    },
  },
  'gemini-cli': {
    name: 'gemini-cli',
    displayName: 'Gemini CLI',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(home, '.gemini'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(home, '.gemini'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(home, '.gemini'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.gemini'));
    },
  },
  'github-copilot': {
    name: 'github-copilot',
    displayName: 'GitHub Copilot',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(home, '.copilot'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(home, '.copilot'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(home, '.copilot'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.github')) ||
        existsSync(join(home, '.copilot'))
      );
    },
  },
  'goose': {
    name: 'goose',
    displayName: 'Goose',
    dirs: {
      skill: { local: '.goose/skills', global: join(join(configHome, 'goose'), 'skills') },
      agent: { local: '.goose/agents', global: join(join(configHome, 'goose'), 'agents') },
      prompt: { local: '.goose/prompts', global: join(join(configHome, 'goose'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(configHome, 'goose'));
    },
  },
  'iflow-cli': {
    name: 'iflow-cli',
    displayName: 'iFlow CLI',
    dirs: {
      skill: { local: '.iflow/skills', global: join(join(home, '.iflow'), 'skills') },
      agent: { local: '.iflow/agents', global: join(join(home, '.iflow'), 'agents') },
      prompt: { local: '.iflow/prompts', global: join(join(home, '.iflow'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.iflow'));
    },
  },
  'junie': {
    name: 'junie',
    displayName: 'Junie',
    dirs: {
      skill: { local: '.junie/skills', global: join(join(home, '.junie'), 'skills') },
      agent: { local: '.junie/agents', global: join(join(home, '.junie'), 'agents') },
      prompt: { local: '.junie/prompts', global: join(join(home, '.junie'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.junie'));
    },
  },
  'kilo': {
    name: 'kilo',
    displayName: 'Kilo Code',
    dirs: {
      skill: { local: '.kilocode/skills', global: join(join(home, '.kilocode'), 'skills') },
      agent: { local: '.kilocode/agents', global: join(join(home, '.kilocode'), 'agents') },
      prompt: { local: '.kilocode/prompts', global: join(join(home, '.kilocode'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.kilocode'));
    },
  },
  'kimi-cli': {
    name: 'kimi-cli',
    displayName: 'Kimi Code CLI',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(home, '.config/agents'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(home, '.config/agents'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(home, '.config/agents'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.kimi'));
    },
  },
  'kiro-cli': {
    name: 'kiro-cli',
    displayName: 'Kiro CLI',
    dirs: {
      skill: { local: '.kiro/skills', global: join(join(home, '.kiro'), 'skills') },
      agent: { local: '.kiro/agents', global: join(join(home, '.kiro'), 'agents') },
      prompt: { local: '.kiro/prompts', global: join(join(home, '.kiro'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.kiro'));
    },
  },
  'kode': {
    name: 'kode',
    displayName: 'Kode',
    dirs: {
      skill: { local: '.kode/skills', global: join(join(home, '.kode'), 'skills') },
      agent: { local: '.kode/agents', global: join(join(home, '.kode'), 'agents') },
      prompt: { local: '.kode/prompts', global: join(join(home, '.kode'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.kode'));
    },
  },
  'mcpjam': {
    name: 'mcpjam',
    displayName: 'MCPJam',
    dirs: {
      skill: { local: '.mcpjam/skills', global: join(join(home, '.mcpjam'), 'skills') },
      agent: { local: '.mcpjam/agents', global: join(join(home, '.mcpjam'), 'agents') },
      prompt: { local: '.mcpjam/prompts', global: join(join(home, '.mcpjam'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.mcpjam'));
    },
  },
  'mistral-vibe': {
    name: 'mistral-vibe',
    displayName: 'Mistral Vibe',
    dirs: {
      skill: { local: '.vibe/skills', global: join(join(home, '.vibe'), 'skills') },
      agent: { local: '.vibe/agents', global: join(join(home, '.vibe'), 'agents') },
      prompt: { local: '.vibe/prompts', global: join(join(home, '.vibe'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.vibe'));
    },
  },
  'mux': {
    name: 'mux',
    displayName: 'Mux',
    dirs: {
      skill: { local: '.mux/skills', global: join(join(home, '.mux'), 'skills') },
      agent: { local: '.mux/agents', global: join(join(home, '.mux'), 'agents') },
      prompt: { local: '.mux/prompts', global: join(join(home, '.mux'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.mux'));
    },
  },
  'neovate': {
    name: 'neovate',
    displayName: 'Neovate',
    dirs: {
      skill: { local: '.neovate/skills', global: join(join(home, '.neovate'), 'skills') },
      agent: { local: '.neovate/agents', global: join(join(home, '.neovate'), 'agents') },
      prompt: { local: '.neovate/prompts', global: join(join(home, '.neovate'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.neovate'));
    },
  },
  'openclaw': {
    name: 'openclaw',
    displayName: 'OpenClaw',
    dirs: {
      skill: { local: 'skills', global: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'skills')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'skills')
        : join(join(home, '.moltbot'), 'skills') },
      agent: { local: 'agents', global: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'agents')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'agents')
        : join(join(home, '.moltbot'), 'agents') },
      prompt: { local: 'prompts', global: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'prompts')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'prompts')
        : join(join(home, '.moltbot'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(home, '.openclaw')) ||
        existsSync(join(home, '.clawdbot')) ||
        existsSync(join(home, '.moltbot'))
      );
    },
  },
  'opencode': {
    name: 'opencode',
    displayName: 'OpenCode',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(configHome, 'opencode'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(configHome, 'opencode'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(configHome, 'opencode'), 'prompts') },
    },
    detectInstalled: async () => {
      return (
        existsSync(join(configHome, 'opencode')) ||
        existsSync(join(claudeHome, 'skills'))
      );
    },
  },
  'openhands': {
    name: 'openhands',
    displayName: 'OpenHands',
    dirs: {
      skill: { local: '.openhands/skills', global: join(join(home, '.openhands'), 'skills') },
      agent: { local: '.openhands/agents', global: join(join(home, '.openhands'), 'agents') },
      prompt: { local: '.openhands/prompts', global: join(join(home, '.openhands'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.openhands'));
    },
  },
  'pi': {
    name: 'pi',
    displayName: 'Pi',
    dirs: {
      skill: { local: '.pi/skills', global: join(join(home, '.pi/agent'), 'skills') },
      agent: { local: '.pi/agents', global: join(join(home, '.pi/agent'), 'agents') },
      prompt: { local: '.pi/prompts', global: join(join(home, '.pi/agent'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.pi/agent'));
    },
  },
  'pochi': {
    name: 'pochi',
    displayName: 'Pochi',
    dirs: {
      skill: { local: '.pochi/skills', global: join(join(home, '.pochi'), 'skills') },
      agent: { local: '.pochi/agents', global: join(join(home, '.pochi'), 'agents') },
      prompt: { local: '.pochi/prompts', global: join(join(home, '.pochi'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.pochi'));
    },
  },
  'qoder': {
    name: 'qoder',
    displayName: 'Qoder',
    dirs: {
      skill: { local: '.qoder/skills', global: join(join(home, '.qoder'), 'skills') },
      agent: { local: '.qoder/agents', global: join(join(home, '.qoder'), 'agents') },
      prompt: { local: '.qoder/prompts', global: join(join(home, '.qoder'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.qoder'));
    },
  },
  'qwen-code': {
    name: 'qwen-code',
    displayName: 'Qwen Code',
    dirs: {
      skill: { local: '.qwen/skills', global: join(join(home, '.qwen'), 'skills') },
      agent: { local: '.qwen/agents', global: join(join(home, '.qwen'), 'agents') },
      prompt: { local: '.qwen/prompts', global: join(join(home, '.qwen'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.qwen'));
    },
  },
  'replit': {
    name: 'replit',
    displayName: 'Replit',
    dirs: {
      skill: { local: '.agents/skills', global: join(join(configHome, 'agents'), 'skills') },
      agent: { local: '.agents/agents', global: join(join(configHome, 'agents'), 'agents') },
      prompt: { local: '.agents/prompts', global: join(join(configHome, 'agents'), 'prompts') },
    },
    showInUniversalList: false,
    detectInstalled: async () => {
      return existsSync(join(process.cwd(), '.agents'));
    },
  },
  'roo': {
    name: 'roo',
    displayName: 'Roo Code',
    dirs: {
      skill: { local: '.roo/skills', global: join(join(home, '.roo'), 'skills') },
      agent: { local: '.roo/agents', global: join(join(home, '.roo'), 'agents') },
      prompt: { local: '.roo/prompts', global: join(join(home, '.roo'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.roo'));
    },
  },
  'trae-cn': {
    name: 'trae-cn',
    displayName: 'Trae CN',
    dirs: {
      skill: { local: '.trae/skills', global: join(join(home, '.trae-cn'), 'skills') },
      agent: { local: '.trae/agents', global: join(join(home, '.trae-cn'), 'agents') },
      prompt: { local: '.trae/prompts', global: join(join(home, '.trae-cn'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.trae-cn'));
    },
  },
  'trae': {
    name: 'trae',
    displayName: 'Trae',
    dirs: {
      skill: { local: '.trae/skills', global: join(join(home, '.trae'), 'skills') },
      agent: { local: '.trae/agents', global: join(join(home, '.trae'), 'agents') },
      prompt: { local: '.trae/prompts', global: join(join(home, '.trae'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.trae'));
    },
  },
  'windsurf': {
    name: 'windsurf',
    displayName: 'Windsurf',
    dirs: {
      skill: { local: '.windsurf/skills', global: join(join(home, '.codeium/windsurf'), 'skills') },
      agent: { local: '.windsurf/agents', global: join(join(home, '.codeium/windsurf'), 'agents') },
      prompt: { local: '.windsurf/prompts', global: join(join(home, '.codeium/windsurf'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.codeium/windsurf'));
    },
  },
  'zencoder': {
    name: 'zencoder',
    displayName: 'Zencoder',
    dirs: {
      skill: { local: '.zencoder/skills', global: join(join(home, '.zencoder'), 'skills') },
      agent: { local: '.zencoder/agents', global: join(join(home, '.zencoder'), 'agents') },
      prompt: { local: '.zencoder/prompts', global: join(join(home, '.zencoder'), 'prompts') },
    },
    detectInstalled: async () => {
      return existsSync(join(home, '.zencoder'));
    },
  },
};
