// AUTO-GENERATED by scripts/compile-agents.ts — DO NOT EDIT
// Source: agents/*.yaml

import { homedir } from 'os';
import { join } from 'path';
import { existsSync } from 'fs';
import { xdgConfig } from 'xdg-basedir';
import type { AgentConfig, AgentType } from '../../../core/types.ts';

const home = homedir();
// Use xdg-basedir (not env-paths) to match OpenCode/Amp/Goose behavior on all platforms.
const configHome = xdgConfig ?? join(home, '.config');
const codexHome = process.env.CODEX_HOME?.trim() || join(home, '.codex');
const claudeHome = process.env.CLAUDE_CONFIG_DIR?.trim() || join(home, '.claude');

export const agents: Record<AgentType, AgentConfig> = {
  'adal': {
    name: 'adal',
    displayName: 'AdaL',
    skillsDir: '.adal/skills',
    globalSkillsDir: join(join(home, '.adal'), 'skills'),
    agentsDir: '.adal/agents',
    globalAgentsDir: join(join(home, '.adal'), 'agents'),
    promptsDir: '.adal/prompts',
    globalPromptsDir: join(join(home, '.adal'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.adal'));
    },
  },
  'amp': {
    name: 'amp',
    displayName: 'Amp',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(configHome, 'agents'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(configHome, 'agents'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(configHome, 'agents'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(configHome, 'amp'));
    },
  },
  'antigravity': {
    name: 'antigravity',
    displayName: 'Antigravity',
    skillsDir: '.agent/skills',
    globalSkillsDir: join(join(home, '.gemini/antigravity'), 'skills'),
    agentsDir: '.agent/agents',
    globalAgentsDir: join(join(home, '.gemini/antigravity'), 'agents'),
    promptsDir: '.agent/prompts',
    globalPromptsDir: join(join(home, '.gemini/antigravity'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.agent')) ||
        existsSync(join(home, '.gemini/antigravity'))
      );
    },
  },
  'augment': {
    name: 'augment',
    displayName: 'Augment',
    skillsDir: '.augment/skills',
    globalSkillsDir: join(join(home, '.augment'), 'skills'),
    agentsDir: '.augment/agents',
    globalAgentsDir: join(join(home, '.augment'), 'agents'),
    promptsDir: '.augment/prompts',
    globalPromptsDir: join(join(home, '.augment'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.augment'));
    },
  },
  'claude-code': {
    name: 'claude-code',
    displayName: 'Claude Code',
    skillsDir: '.claude/skills',
    globalSkillsDir: join(claudeHome, 'skills'),
    agentsDir: '.claude/agents',
    globalAgentsDir: join(claudeHome, 'agents'),
    promptsDir: '.claude/prompts',
    globalPromptsDir: join(claudeHome, 'prompts'),
    detectInstalled: async () => {
      return existsSync(claudeHome);
    },
  },
  'cline': {
    name: 'cline',
    displayName: 'Cline',
    skillsDir: '.cline/skills',
    globalSkillsDir: join(join(home, '.cline'), 'skills'),
    agentsDir: '.cline/agents',
    globalAgentsDir: join(join(home, '.cline'), 'agents'),
    promptsDir: '.cline/prompts',
    globalPromptsDir: join(join(home, '.cline'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.cline'));
    },
  },
  'codebuddy': {
    name: 'codebuddy',
    displayName: 'CodeBuddy',
    skillsDir: '.codebuddy/skills',
    globalSkillsDir: join(join(home, '.codebuddy'), 'skills'),
    agentsDir: '.codebuddy/agents',
    globalAgentsDir: join(join(home, '.codebuddy'), 'agents'),
    promptsDir: '.codebuddy/prompts',
    globalPromptsDir: join(join(home, '.codebuddy'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.codebuddy')) ||
        existsSync(join(home, '.codebuddy'))
      );
    },
  },
  'codex': {
    name: 'codex',
    displayName: 'Codex',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(codexHome, 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(codexHome, 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(codexHome, 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(codexHome) ||
        existsSync('/etc/codex')
      );
    },
  },
  'command-code': {
    name: 'command-code',
    displayName: 'Command Code',
    skillsDir: '.commandcode/skills',
    globalSkillsDir: join(join(home, '.commandcode'), 'skills'),
    agentsDir: '.commandcode/agents',
    globalAgentsDir: join(join(home, '.commandcode'), 'agents'),
    promptsDir: '.commandcode/prompts',
    globalPromptsDir: join(join(home, '.commandcode'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.commandcode'));
    },
  },
  'continue': {
    name: 'continue',
    displayName: 'Continue',
    skillsDir: '.continue/skills',
    globalSkillsDir: join(join(home, '.continue'), 'skills'),
    agentsDir: '.continue/agents',
    globalAgentsDir: join(join(home, '.continue'), 'agents'),
    promptsDir: '.continue/prompts',
    globalPromptsDir: join(join(home, '.continue'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.continue')) ||
        existsSync(join(home, '.continue'))
      );
    },
  },
  'crush': {
    name: 'crush',
    displayName: 'Crush',
    skillsDir: '.crush/skills',
    globalSkillsDir: join(join(home, '.config/crush'), 'skills'),
    agentsDir: '.crush/agents',
    globalAgentsDir: join(join(home, '.config/crush'), 'agents'),
    promptsDir: '.crush/prompts',
    globalPromptsDir: join(join(home, '.config/crush'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.config/crush'));
    },
  },
  'cursor': {
    name: 'cursor',
    displayName: 'Cursor',
    skillsDir: '.cursor/skills',
    globalSkillsDir: join(join(home, '.cursor'), 'skills'),
    agentsDir: '.cursor/agents',
    globalAgentsDir: join(join(home, '.cursor'), 'agents'),
    promptsDir: '.cursor/prompts',
    globalPromptsDir: join(join(home, '.cursor'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.cursor'));
    },
  },
  'droid': {
    name: 'droid',
    displayName: 'Droid',
    skillsDir: '.factory/skills',
    globalSkillsDir: join(join(home, '.factory'), 'skills'),
    agentsDir: '.factory/agents',
    globalAgentsDir: join(join(home, '.factory'), 'agents'),
    promptsDir: '.factory/prompts',
    globalPromptsDir: join(join(home, '.factory'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.factory'));
    },
  },
  'gemini-cli': {
    name: 'gemini-cli',
    displayName: 'Gemini CLI',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(home, '.gemini'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(home, '.gemini'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(home, '.gemini'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.gemini'));
    },
  },
  'github-copilot': {
    name: 'github-copilot',
    displayName: 'GitHub Copilot',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(home, '.copilot'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(home, '.copilot'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(home, '.copilot'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(process.cwd(), '.github')) ||
        existsSync(join(home, '.copilot'))
      );
    },
  },
  'goose': {
    name: 'goose',
    displayName: 'Goose',
    skillsDir: '.goose/skills',
    globalSkillsDir: join(join(configHome, 'goose'), 'skills'),
    agentsDir: '.goose/agents',
    globalAgentsDir: join(join(configHome, 'goose'), 'agents'),
    promptsDir: '.goose/prompts',
    globalPromptsDir: join(join(configHome, 'goose'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(configHome, 'goose'));
    },
  },
  'iflow-cli': {
    name: 'iflow-cli',
    displayName: 'iFlow CLI',
    skillsDir: '.iflow/skills',
    globalSkillsDir: join(join(home, '.iflow'), 'skills'),
    agentsDir: '.iflow/agents',
    globalAgentsDir: join(join(home, '.iflow'), 'agents'),
    promptsDir: '.iflow/prompts',
    globalPromptsDir: join(join(home, '.iflow'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.iflow'));
    },
  },
  'junie': {
    name: 'junie',
    displayName: 'Junie',
    skillsDir: '.junie/skills',
    globalSkillsDir: join(join(home, '.junie'), 'skills'),
    agentsDir: '.junie/agents',
    globalAgentsDir: join(join(home, '.junie'), 'agents'),
    promptsDir: '.junie/prompts',
    globalPromptsDir: join(join(home, '.junie'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.junie'));
    },
  },
  'kilo': {
    name: 'kilo',
    displayName: 'Kilo Code',
    skillsDir: '.kilocode/skills',
    globalSkillsDir: join(join(home, '.kilocode'), 'skills'),
    agentsDir: '.kilocode/agents',
    globalAgentsDir: join(join(home, '.kilocode'), 'agents'),
    promptsDir: '.kilocode/prompts',
    globalPromptsDir: join(join(home, '.kilocode'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.kilocode'));
    },
  },
  'kimi-cli': {
    name: 'kimi-cli',
    displayName: 'Kimi Code CLI',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(home, '.config/agents'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(home, '.config/agents'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(home, '.config/agents'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.kimi'));
    },
  },
  'kiro-cli': {
    name: 'kiro-cli',
    displayName: 'Kiro CLI',
    skillsDir: '.kiro/skills',
    globalSkillsDir: join(join(home, '.kiro'), 'skills'),
    agentsDir: '.kiro/agents',
    globalAgentsDir: join(join(home, '.kiro'), 'agents'),
    promptsDir: '.kiro/prompts',
    globalPromptsDir: join(join(home, '.kiro'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.kiro'));
    },
  },
  'kode': {
    name: 'kode',
    displayName: 'Kode',
    skillsDir: '.kode/skills',
    globalSkillsDir: join(join(home, '.kode'), 'skills'),
    agentsDir: '.kode/agents',
    globalAgentsDir: join(join(home, '.kode'), 'agents'),
    promptsDir: '.kode/prompts',
    globalPromptsDir: join(join(home, '.kode'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.kode'));
    },
  },
  'mcpjam': {
    name: 'mcpjam',
    displayName: 'MCPJam',
    skillsDir: '.mcpjam/skills',
    globalSkillsDir: join(join(home, '.mcpjam'), 'skills'),
    agentsDir: '.mcpjam/agents',
    globalAgentsDir: join(join(home, '.mcpjam'), 'agents'),
    promptsDir: '.mcpjam/prompts',
    globalPromptsDir: join(join(home, '.mcpjam'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.mcpjam'));
    },
  },
  'mistral-vibe': {
    name: 'mistral-vibe',
    displayName: 'Mistral Vibe',
    skillsDir: '.vibe/skills',
    globalSkillsDir: join(join(home, '.vibe'), 'skills'),
    agentsDir: '.vibe/agents',
    globalAgentsDir: join(join(home, '.vibe'), 'agents'),
    promptsDir: '.vibe/prompts',
    globalPromptsDir: join(join(home, '.vibe'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.vibe'));
    },
  },
  'mux': {
    name: 'mux',
    displayName: 'Mux',
    skillsDir: '.mux/skills',
    globalSkillsDir: join(join(home, '.mux'), 'skills'),
    agentsDir: '.mux/agents',
    globalAgentsDir: join(join(home, '.mux'), 'agents'),
    promptsDir: '.mux/prompts',
    globalPromptsDir: join(join(home, '.mux'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.mux'));
    },
  },
  'neovate': {
    name: 'neovate',
    displayName: 'Neovate',
    skillsDir: '.neovate/skills',
    globalSkillsDir: join(join(home, '.neovate'), 'skills'),
    agentsDir: '.neovate/agents',
    globalAgentsDir: join(join(home, '.neovate'), 'agents'),
    promptsDir: '.neovate/prompts',
    globalPromptsDir: join(join(home, '.neovate'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.neovate'));
    },
  },
  'openclaw': {
    name: 'openclaw',
    displayName: 'OpenClaw',
    skillsDir: 'skills',
    globalSkillsDir: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'skills')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'skills')
        : join(join(home, '.moltbot'), 'skills'),
    agentsDir: 'agents',
    globalAgentsDir: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'agents')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'agents')
        : join(join(home, '.moltbot'), 'agents'),
    promptsDir: 'prompts',
    globalPromptsDir: existsSync(join(home, '.openclaw'))
        ? join(join(home, '.openclaw'), 'prompts')
        : existsSync(join(home, '.clawdbot'))
        ? join(join(home, '.clawdbot'), 'prompts')
        : join(join(home, '.moltbot'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(home, '.openclaw')) ||
        existsSync(join(home, '.clawdbot')) ||
        existsSync(join(home, '.moltbot'))
      );
    },
  },
  'opencode': {
    name: 'opencode',
    displayName: 'OpenCode',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(configHome, 'opencode'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(configHome, 'opencode'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(configHome, 'opencode'), 'prompts'),
    detectInstalled: async () => {
      return (
        existsSync(join(configHome, 'opencode')) ||
        existsSync(join(claudeHome, 'skills'))
      );
    },
  },
  'openhands': {
    name: 'openhands',
    displayName: 'OpenHands',
    skillsDir: '.openhands/skills',
    globalSkillsDir: join(join(home, '.openhands'), 'skills'),
    agentsDir: '.openhands/agents',
    globalAgentsDir: join(join(home, '.openhands'), 'agents'),
    promptsDir: '.openhands/prompts',
    globalPromptsDir: join(join(home, '.openhands'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.openhands'));
    },
  },
  'pi': {
    name: 'pi',
    displayName: 'Pi',
    skillsDir: '.pi/skills',
    globalSkillsDir: join(join(home, '.pi/agent'), 'skills'),
    agentsDir: '.pi/agents',
    globalAgentsDir: join(join(home, '.pi/agent'), 'agents'),
    promptsDir: '.pi/prompts',
    globalPromptsDir: join(join(home, '.pi/agent'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.pi/agent'));
    },
  },
  'pochi': {
    name: 'pochi',
    displayName: 'Pochi',
    skillsDir: '.pochi/skills',
    globalSkillsDir: join(join(home, '.pochi'), 'skills'),
    agentsDir: '.pochi/agents',
    globalAgentsDir: join(join(home, '.pochi'), 'agents'),
    promptsDir: '.pochi/prompts',
    globalPromptsDir: join(join(home, '.pochi'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.pochi'));
    },
  },
  'qoder': {
    name: 'qoder',
    displayName: 'Qoder',
    skillsDir: '.qoder/skills',
    globalSkillsDir: join(join(home, '.qoder'), 'skills'),
    agentsDir: '.qoder/agents',
    globalAgentsDir: join(join(home, '.qoder'), 'agents'),
    promptsDir: '.qoder/prompts',
    globalPromptsDir: join(join(home, '.qoder'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.qoder'));
    },
  },
  'qwen-code': {
    name: 'qwen-code',
    displayName: 'Qwen Code',
    skillsDir: '.qwen/skills',
    globalSkillsDir: join(join(home, '.qwen'), 'skills'),
    agentsDir: '.qwen/agents',
    globalAgentsDir: join(join(home, '.qwen'), 'agents'),
    promptsDir: '.qwen/prompts',
    globalPromptsDir: join(join(home, '.qwen'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.qwen'));
    },
  },
  'replit': {
    name: 'replit',
    displayName: 'Replit',
    skillsDir: '.agents/skills',
    globalSkillsDir: join(join(configHome, 'agents'), 'skills'),
    agentsDir: '.agents/agents',
    globalAgentsDir: join(join(configHome, 'agents'), 'agents'),
    promptsDir: '.agents/prompts',
    globalPromptsDir: join(join(configHome, 'agents'), 'prompts'),
    showInUniversalList: false,
    detectInstalled: async () => {
      return existsSync(join(process.cwd(), '.agents'));
    },
  },
  'roo': {
    name: 'roo',
    displayName: 'Roo Code',
    skillsDir: '.roo/skills',
    globalSkillsDir: join(join(home, '.roo'), 'skills'),
    agentsDir: '.roo/agents',
    globalAgentsDir: join(join(home, '.roo'), 'agents'),
    promptsDir: '.roo/prompts',
    globalPromptsDir: join(join(home, '.roo'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.roo'));
    },
  },
  'trae-cn': {
    name: 'trae-cn',
    displayName: 'Trae CN',
    skillsDir: '.trae/skills',
    globalSkillsDir: join(join(home, '.trae-cn'), 'skills'),
    agentsDir: '.trae/agents',
    globalAgentsDir: join(join(home, '.trae-cn'), 'agents'),
    promptsDir: '.trae/prompts',
    globalPromptsDir: join(join(home, '.trae-cn'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.trae-cn'));
    },
  },
  'trae': {
    name: 'trae',
    displayName: 'Trae',
    skillsDir: '.trae/skills',
    globalSkillsDir: join(join(home, '.trae'), 'skills'),
    agentsDir: '.trae/agents',
    globalAgentsDir: join(join(home, '.trae'), 'agents'),
    promptsDir: '.trae/prompts',
    globalPromptsDir: join(join(home, '.trae'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.trae'));
    },
  },
  'windsurf': {
    name: 'windsurf',
    displayName: 'Windsurf',
    skillsDir: '.windsurf/skills',
    globalSkillsDir: join(join(home, '.codeium/windsurf'), 'skills'),
    agentsDir: '.windsurf/agents',
    globalAgentsDir: join(join(home, '.codeium/windsurf'), 'agents'),
    promptsDir: '.windsurf/prompts',
    globalPromptsDir: join(join(home, '.codeium/windsurf'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.codeium/windsurf'));
    },
  },
  'zencoder': {
    name: 'zencoder',
    displayName: 'Zencoder',
    skillsDir: '.zencoder/skills',
    globalSkillsDir: join(join(home, '.zencoder'), 'skills'),
    agentsDir: '.zencoder/agents',
    globalAgentsDir: join(join(home, '.zencoder'), 'agents'),
    promptsDir: '.zencoder/prompts',
    globalPromptsDir: join(join(home, '.zencoder'), 'prompts'),
    detectInstalled: async () => {
      return existsSync(join(home, '.zencoder'));
    },
  },
};
