import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import type { Skill } from './types.ts';
import { sanitizeName } from './installer.ts';

/**
 * Windows On-Device Registry (ODR) artifact emitter.
 *
 * Emits the JSON + appxmanifest-fragment that a Windows MSIX packager needs
 * to register a skill as an Agent Launcher on Windows 11.
 *
 * IMPORTANT: this is emit-only. The CLI does NOT call odr.exe; doing so
 * requires package identity which an unpackaged Node process cannot acquire.
 * See https://learn.microsoft.com/en-us/windows/ai/agent-launchers/agents-get-started
 * ("Due to package identity requirements, you can't use `agent-info add`
 * and `agent-info remove` from an unpackaged app").
 *
 * The emitted JSON conforms to the schema documented at the URL above. Only
 * the fields the docs define are written. The `action_id` is left as a
 * `{{ACTION_ID}}` template because it must match an App Action `id` defined
 * by the packager's own App Actions provider, which lives outside this CLI.
 */

const SUBDIR = 'windows-odr';

interface FrontmatterFields {
  name?: string;
  description?: string;
  version?: string;
}

function pickFrontmatter(skill: Skill): FrontmatterFields {
  const md = (skill.metadata ?? {}) as Record<string, unknown>;
  return {
    name: typeof md.name === 'string' ? md.name : skill.name,
    description: typeof md.description === 'string' ? md.description : skill.description,
    version: typeof md.version === 'string' ? md.version : undefined,
  };
}

function buildAgentRegistration(skill: Skill): Record<string, string> {
  const fm = pickFrontmatter(skill);
  const idName = sanitizeName(fm.name ?? skill.name);
  return {
    manifest_version: '0.1.0',
    version: fm.version ?? '1.0.0',
    name: idName,
    display_name: fm.name ?? idName,
    description: fm.description ?? '',
    placeholder_text: 'What can you help me with?',
    icon: '{{ICON_PATH}}',
    action_id: '{{ACTION_ID}}',
  };
}

function buildAppxFragment(skill: Skill): string {
  const idName = sanitizeName(skill.name);
  return `<!--
  Append the following two <uap3:Extension> blocks inside the <Extensions>
  element of your MSIX Package.appxmanifest.

  The first block registers the App Action that backs this agent. You must
  implement the action's StartXxxAgent handler in your packaged app's code.
  The second block registers the agent itself and points at the JSON file
  emitted alongside this fragment.

  Substitute placeholders:
    {{ACTION_ID}}    must match the action_id in agentRegistration.json
                     and the [WindowsAction(Id=...)] in your provider code
    {{PUBLIC_DIR}}   folder inside your package that holds the JSON
                     (e.g. "Assets")
-->

<uap3:Extension Category="windows.appExtension">
    <uap3:AppExtension
      Name="com.microsoft.windows.ai.actions"
      Id="{{ACTION_ID}}"
      DisplayName="${idName}"
      PublicFolder="{{PUBLIC_DIR}}">
      <uap3:Properties>
        <!-- App Actions definition file generated by your provider build -->
        <Registration>actions.json</Registration>
      </uap3:Properties>
    </uap3:AppExtension>
</uap3:Extension>

<uap3:Extension Category="windows.appExtension">
    <uap3:AppExtension
      Name="com.microsoft.windows.ai.agentInfo"
      Id="${idName}"
      DisplayName="${idName}"
      PublicFolder="{{PUBLIC_DIR}}">
      <uap3:Properties>
        <Registration>agentRegistration.json</Registration>
      </uap3:Properties>
    </uap3:AppExtension>
</uap3:Extension>
`;
}

function buildReadme(skill: Skill): string {
  const idName = sanitizeName(skill.name);
  return `# Windows ODR artifacts for \`${idName}\`

These files let a Windows MSIX packager register this skill as an
Agent Launcher in the Windows 11 On-Device Registry (ODR).

This directory was emitted by \`npx skills add --emit-windows-odr\`.
The \`npx skills\` CLI itself does **not** register anything with Windows:
\`odr.exe agent-info add\` requires package identity, which an unpackaged
Node process cannot acquire. See the Microsoft docs for the constraint:
<https://learn.microsoft.com/en-us/windows/ai/agent-launchers/agents-get-started>.

## Files

- \`agentRegistration.json\` — the agent definition manifest. \`action_id\`
  and \`icon\` are left as \`{{ACTION_ID}}\` / \`{{ICON_PATH}}\` placeholders.
- \`Package.appxmanifest.fragment.xml\` — \`<uap3:Extension>\` blocks for
  both the backing App Action and the Agent Launcher itself. Paste these
  into your MSIX's \`Package.appxmanifest\` under \`<Extensions>\`.

## To register this skill on Windows 11

1. Author an App Actions provider in your MSIX project whose
   \`[WindowsAction(Id = "...")]\` matches the \`{{ACTION_ID}}\` you
   substitute below. The provider's invocation handler is what actually
   launches your agent UI.
2. Copy \`agentRegistration.json\` into your project's \`Assets\` folder
   (or any \`PublicFolder\` you declare).
3. Substitute \`{{ACTION_ID}}\` and \`{{ICON_PATH}}\` in
   \`agentRegistration.json\`.
4. Paste the contents of \`Package.appxmanifest.fragment.xml\` into your
   \`Package.appxmanifest\` and substitute \`{{ACTION_ID}}\` and
   \`{{PUBLIC_DIR}}\`.
5. Build, sign, and install the MSIX. Static registration completes at
   install time; no \`odr.exe\` call is required.

Verify with:

\`\`\`powershell
odr agent-info list
\`\`\`
`;
}

/**
 * Emit Windows ODR registration artifacts for a single skill into
 * `<destDir>/windows-odr/`.
 *
 * Safe to call on any platform; the files are inert until packaged.
 */
export async function emitWindowsOdrArtifacts(skill: Skill, destDir: string): Promise<string> {
  const outDir = join(destDir, SUBDIR);
  await mkdir(outDir, { recursive: true });

  const registration = buildAgentRegistration(skill);
  await writeFile(
    join(outDir, 'agentRegistration.json'),
    JSON.stringify(registration, null, 2) + '\n',
    'utf-8'
  );
  await writeFile(
    join(outDir, 'Package.appxmanifest.fragment.xml'),
    buildAppxFragment(skill),
    'utf-8'
  );
  await writeFile(join(outDir, 'README.md'), buildReadme(skill), 'utf-8');

  return outDir;
}
